name: Code Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: ruff
        run: uv run --group check ruff check .
      - name: black
        run: uv run --group check black --check .
      - name: interrogate
        run: uv run --group check interrogate app/services -vv
